project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!internal/"

website:
  title: "2023 Agricultural Hackathon"
  image: rwds-logo-150px.png
  favicon: images/favicon.png
  open-graph: true
  site-url:  https://idahoagstats.github.io/AgHackathon
  #repo-url: https://github.com/IdahoAgStats/AgHackathon
  #repo-actions: [edit, issue]
  google-analytics: "G-ZZST40VXE1"
  navbar:
    background: "#F4F4EC"
    logo: images/hackathon_header.png
    title: false
    collapse-below: lg
    right:
      - text: "Topic"
        href: topic.qmd
      - text: "Workshops"
        href: workshops.qmd
      - text: "Competition"
        menu: 
        - text: "Schedule"
          href: schedule.qmd
        - text: "Rules"
          href: rules.qmd
        - text: "rubric"
          href: rubric.qmd
      - text: "Register"
        href: signup.qmd
      - text: "About"
        href: about.qmd
        
  page-navigation: true

  #back-to-top-navigation: false

  page-footer:
    background: "#aba96d"
    left:    |
      [![](https://github.com/IdahoAgStats/AgHackathon/raw/main/images/github-mark-white.png){width=70px}](https://github.com/IdahoAgStats/AgHackathon){target="_blank"}
    center:  |
      [![](https://github.com/IdahoAgStats/AgHackathon/raw/main/images/open_science_logo.png){width=250px}](https://www.acsmeetings.org/){target="_blank"}
    right: |
      [![](https://github.com/IdahoAgStats/AgHackathon/raw/main/images/john_deere_logo.png){fig-alt="John Deere Logo" width=200px}](https://www.deere.com/en/){target="_blank"}
      [![](https://github.com/IdahoAgStats/AgHackathon/raw/main/images/syngenta_logo_transparent.png){fig-alt="Syngenta Seeds Logo" width=200px}](https://www.syngenta-us.com/seed/){target="_blank"}
    
format:
  html:
    theme: [rwds.scss, lux]
    css: rwds.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto
  