project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!internal/"

website:
  title: "2023 Agricultural Hackathon"
  image: images/AgHackathon_logo.png
  favicon: images/favicon.png
  open-graph: true
  site-url:  idahoagstats.github.io/AgHackathon/ 
  #repo-url: https://github.com/IdahoAgStats/AgHackathon
  #repo-actions: [edit, issue]
  #google-analytics: "G-1TTWB7YTR6"
  navbar:
    background: "#F4F4EC"
    logo: images/AgHackathon_logo.png
    logo-alt: "AgHackathon Logo"
    title: false
    collapse-below: lg
    right:
      - text: "Topic"
        href: topic.qmd
      - text: "Rules"
        href: rules.qmd
      - text: "Schedule"
        href: schedule.qmd
      - text: "About"
        href: about.qmd
        
  page-navigation: true

  #back-to-top-navigation: false

  page-footer:
    background: "#aba96d"
    left: 
        - href: https://github.com/IdahoAgStats/AgHackathon
          icon: github
          aria-label: GitHub
    center:  |
      [![](https://github.com/IdahoAgStats/AgHackathon/blob/main/images/open_science_logo.png){fig-alt="ASA-CSSA-SSSA 2023 Meetings Logo" width=200px}](https://www.acsmeetings.org/)
    right: |
      [![](https://github.com/IdahoAgStats/AgHackathon/blob/main/images/syngenta_logo_transparent.png){fig-alt="Syngenta Seeds Logo" width=200px}](https://www.acsmeetings.org/)
    
format:
  html:
    theme: [lux, rwds.scss]
    css: rwds.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto
  